### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/george-du-maurier_trilby#1]
# General Issues:

- [ ] Re-run `se typogrify .` and commit some of the changes (add no-break spaces).

- [x] Re-run `se semanticate .` and commit some of the changes (add semantics to abbreviations).

- [x] Because these chapters are called parts, the file names and ids should look like `part-#.xhtml` and `part-#`. You can keep the `chapter` semantics.

- [x] The part headers need to be formatted with roman numerals and semantics. Look at the example in [SEMOS 7.2.4](https://standardebooks.org/manual/1.7.3/single-page#7.2.4) to see how the part headers should look. In Part V's header, `Little Billee` should be tagged as `title`.

- Make sure to re-run `se build-title .` `se build-manifest .`, `se build-spine .`, and `se build-toc .` after updating the file names, ids, and headers.

- [x] You don't need both double and single quotes around verse. You can just use double quotes.

- [x] "Ach!" is a common interjection found in multiple languages. You can replace `<i xml:lang="de">Ach!</i>` with `<em>Ach!</em>`.

# chapter-1.xhtml:

- [x] Remove italics around `monsieur`, since it's in MW.

# chapter-2.xhtml:

- [x] Remove italics around `persona gratissima`, since it's in MW.

- [x] For the section `“Chez Carrel.”`, wrap the `<header>` and following text in a `<section>` element. Remove the `<div>` and period in the header. This can be given `subchapter` semantics.

# chapter-5.xhtml:

- [x] Remove the extra exclamation mark in `<i xml:lang="fr">dans le pays du tendre!</i>!`. Restore the quotes around the phrase.

# chapter-6.xhtml:

- [x] The epigraph needs to start with double quotes.

# chapter-8.xhtml:

- [x] For the section `Vingt Ans Après`, wrap the `<header>` and following text in a `<section>` element. Remove the `<div>`. This can be given `subchapter` semantics.

- [x] The `<header>` can be simplified as:
```
				<header>
					<p xml:lang="fr">Vingt Ans Après</p>
				</header>
```

# local.css:

- [x] For styling the subchapters, you can use:
```
section[epub|type~="subchapter"]{
	padding-top: 2em;
}

section[epub|type~="subchapter"] header{
	font-variant: small-caps;
	margin: 1em;
	text-align: center;
}
```

**Comment by javamanatee** [comment]
I'm almost done working through the issues.  For typogrify no-break spaces, I think you mean the line with
"And then, the first act over, Mr. and Mrs. Wynne leave the theatre; Mr. explaining why, and Mrs. very ready to go,..."

I kept normal spaces for "Mr. explaining why, and Mrs. very ready" since it did not seem that these abbrs connect to any target.  Do you agree? Unless I'm just parsing it wrong.

**Comment by EmmaSweeney** [comment]
Ok, you can leave that as-is.

**Comment by javamanatee** [comment]
This is ready for you to take another look.
